#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import argparse
import copy
import os

import pandas as pd
import pytz
from inicheck.tools import get_user_config, cast_all_variables
from smrf.utils import utils

from awsm.framework.framework import run_awsm, run_awsm_daily_ops

DATE_FORMAT = '%Y%m%d'
DATE_TIME_FORMAT = '%Y-%m-%d %H:%M'
ADD_DAY = pd.to_timedelta(23, unit='h')


def output_for_date(config, date):
    """
    Get absolute folder path for model output of a date

    Parameters
    ----------
    config: UserConfig
        Parsed user config holding path information
    date : datetime
        Date to generate path for

    Returns
    -------
    str
        Absolute path to output folder
    """
    # Get the water year
    tzinfo = pytz.timezone(config.cfg['time']['time_zone'])
    wy = utils.water_day(date.replace(tzinfo=tzinfo))[1]

    # Get base output location
    paths = config.cfg['paths']
    base_output = os.path.join(
        paths['path_dr'],
        paths['basin'],
        'wy{}'.format(wy),
        paths['project_name'],
    )

    return os.path.join(
            base_output,
            f'run{format(date.strftime(DATE_FORMAT))}',
        )

def mod_config(
    config_file, start_date, no_previous, threshold, medium_threshold
):
    """
    Modify the configuration file to run for a single day

    Parameters
    ----------
    config_file : str
        Full path to .ini file
    start_date : str
        Day to run
    no_previous : bool
        Should the previous day be used to initialize the model
    threshold : bool
        Run model with different mass threshold
    medium_threshold : int
        Medium mass threshold value

    Returns
    -------
    UserConfig
        Updated user config (.ini file) to use for the model run
    """
    start_date = pd.to_datetime(start_date)

    # Get config instance and parse all values for AWSM and SMRF
    config = get_user_config(config_file, modules=['smrf', 'awsm'])
    config.apply_recipes()
    config = cast_all_variables(config, config.mcfg)

    # Prepare new configuration
    new_config = copy.deepcopy(config)

    # Set the start and end dates
    start_date = start_date
    end_date = start_date + ADD_DAY
    new_config.raw_cfg['time']['start_date'] = start_date.strftime(
        DATE_TIME_FORMAT
    )
    new_config.raw_cfg['time']['end_date'] = end_date.strftime(DATE_TIME_FORMAT)

    if no_previous:
        # Run without initialization from previous day
        new_config.raw_cfg['files']['init_type'] = None
        new_config.raw_cfg['files']['init_file'] = None
    else:
        # Find previous snow.nc and storm_days.nc
        prev_day = start_date - pd.to_timedelta(1, unit='D')
        previous_day_output = output_for_date(new_config, prev_day)

        new_config.raw_cfg['files']['init_type'] = 'netcdf_out'
        new_config.raw_cfg['files']['init_file'] = os.path.join(
            previous_day_output, 'snow.nc'
        )

        new_config.raw_cfg['precip']['storm_days_restart'] = os.path.join(
            previous_day_output, 'storm_days.nc'
        )

    if threshold:
        new_config.raw_cfg['grid']['thresh_medium'] = medium_threshold
        print(
            f"** Running model with medium mass theshold of: {medium_threshold}"
        )
        # No need to run SMRF again when changing the mass threshold for iSnobal
        new_config.raw_cfg['awsm master']['run_smrf'] = False

        # Remove files from previous runs before attempting a re-run
        current_day_output = output_for_date(new_config, start_date)

        snow_nc = os.path.join(current_day_output, 'snow.nc')
        if os.path.exists(snow_nc):
            os.remove(snow_nc)

        em_nc = os.path.join(current_day_output, 'em.nc')
        if os.path.exists(em_nc):
            os.remove(em_nc)

    return new_config


def parse_arguments():
    parser = argparse.ArgumentParser(
        description='Run AWSM for a single day'
    )

    parser.add_argument(
        '-c', '--config-file',
        required=True,
        help='Config file that will be modified for the current run date'
    )
    parser.add_argument(
        '-sd', '--start_date',
        required=False,
        default=None,
        help='start date for run'
    )
    parser.add_argument(
        "-np", "--no_previous",
        action="store_true",
        default=False,
        help="Doesn't need to find a previous snow state "
             "from directory structure"
    )
    parser.add_argument(
        '-t', '--threshold',
        action="store_true",
        default=False,
        help='Run iSnobal with different mass threshold'
    )
    parser.add_argument(
        '-mt', '--medium-threshold',
        type=int,
        default=25,
        help='Medium mass threshold. Default: 25'
    )

    return parser.parse_args()


if __name__ == '__main__':
    args = parse_arguments()

    # Run a single day only when given a start date via parameters
    if args.start_date is not None:
        # set dates and paths
        new_config = mod_config(
            args.config_file,
            args.start_date,
            args.no_previous,
            args.threshold,
            args.medium_threshold,
        )

        # apply recipes with new settings
        new_config.apply_recipes()
        new_config = cast_all_variables(new_config, new_config.mcfg)

        run_awsm(new_config)
    else:
        run_awsm_daily_ops(args.config_file)
